name: Pull file from s3
on: workflow_dispatch

jobs:
  pull_from_s3:
    runs-on: ubuntu-latest
    steps:
      - name: ssh to server
        uses: appleboy/ssh-action@master
        with:
          host: 13.251.16.93
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            whoami
            ls -al
      # - name: "AWS CLI"
      #   uses: ItsKarma/aws-cli@v1.70.0
